# Current powerline solution: use spaces instead of \b to overwrite
# See: https://github.com/starship/starship/issues/528

format = """
$status$jobs[ λ ](bg:yellow fg:black bold)[](bg:black fg:yellow)$directory$git_branch$git_status$git_commit$git_state$package$cmd_duration """

# Disable the newline at the start of the prompt
add_newline = false

[status]
style = "fg:red bold"
format = "[$symbol ]($style)"
disabled = false

[jobs]
symbol = "⚙"
style = "fg:cyan bold"

[directory]
# use bg:none to flex my bugfix
format = "[](bg:cyan fg:black)[ $path ]($style)[$read_only]($read_only_style)[](cyan)"
style = "bg:cyan fg:black bold"
read_only_style = "bg:cyan fg:red"

#TODO: make the background colour change
[git_branch]
format = "[](bg:red fg:black)[ $symbol$branch ]($style)[](red)"
style = "bg:red fg:black bold"

[git_status]
format = "(\b[$all_status$ahead_behind ]($style)[](red))"
style = "bg:red fg:black bold"
staged = "✚"
modified = "●"

[git_commit]
format = "(\b[\\($hash\\)]($style)([\\($tag\\)]($style))[ ]($style)[](red))"
style = "bg:red fg:green green bold"
only_detached = true

[git_state]
format = "([$state( $progress_current/$progress_total)]($style))[ ]($style)[](red)"
style = "bg:red fg:black bold"

[package]
format = "[](bg:yellow fg:black)[ $symbol$version]($style)[ ]($style)[](yellow)"
style = "bg:yellow fg:black bold"

[cmd_duration]
format = "[ $duration]($style)"
